// Generated by CoffeeScript 1.7.1
(function() {
  var assert, backlog, cloud, draw, draw_hl_fade, draw_status, focus, k, tags, v, vis, _ref,
    __hasProp = {}.hasOwnProperty;

  assert = function(condition, message) {
    if (!condition) {
      throw message || 'Assertion failed';
    }
  };

  tags = {
    indexed: ffhome_tags,
    sorted: ((function() {
      var _results;
      _results = [];
      for (k in ffhome_tags) {
        if (!__hasProp.call(ffhome_tags, k)) continue;
        v = ffhome_tags[k];
        _results.push({
          tag: k,
          value: v.value,
          links: v.links
        });
      }
      return _results;
    })()).sort(function(a, b) {
      return b.value - a.value;
    }),
    links_box: d3.select('#tag-links'),
    edges: {
      sorted: ffhome_tag_edges.sort(function(a, b) {
        return a[2] - b[2];
      }),
      indexed: (function() {
        var index, t1, t2, _i, _j, _len, _len1, _ref, _ref1, _ref2;
        index = {};
        for (_i = 0, _len = ffhome_tag_edges.length; _i < _len; _i++) {
          _ref = ffhome_tag_edges[_i], t1 = _ref[0], t2 = _ref[1], v = _ref[2];
          _ref1 = [[t1, t2], [t2, t1]];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            _ref2 = _ref1[_j], t1 = _ref2[0], t2 = _ref2[1];
            if (index[t1] == null) {
              index[t1] = {};
            }
            index[t1][t2] = v;
          }
        }
        return index;
      })()
    },
    highlight: null
  };

  vis = {
    fill: d3.scale.category20(),
    box: d3.select('#vis'),
    data: null,
    status: d3.select('#vis-status div'),
    status_counter: 0,
    opacity: {
      highlight: 1,
      unrelated: 0.1,
      scale: d3.scale.sqrt().range([0.2, 0.9])
    }
  };

  _ref = [vis.box.node().clientWidth, vis.box.node().clientHeight], vis.w = _ref[0], vis.h = _ref[1];

  vis.svg = vis.box.select('svg').attr('width', vis.w).attr('height', vis.h);

  vis.bg = vis.svg.append('g').classed({
    background: true
  });

  vis.cloud = vis.svg.append('g').classed({
    'tag-cloud': true
  }).attr('transform', 'translate(' + [vis.w >> 1, vis.h >> 1] + ')');

  vis.graph = vis.svg.append('g').classed({
    'tag-graph': true
  });

  assert(vis.h > 100 && vis.w > 100, vis);

  vis.font_scale = vis.box.style('font-size');

  assert(vis.font_scale.match(/px$/), vis);

  vis.font_scale = parseInt(vis.font_scale);

  vis.font_scale = d3.scale.linear().range([vis.font_scale, vis.font_scale * 3]).domain([+tags.sorted[tags.sorted.length - 1].value, +tags.sorted[0].value]);

  draw_hl_fade = function(selection) {
    var a, b, edges, hl_check, opacity_scale, _ref1;
    assert((selection != null) || vis.data);
    hl_check = function(d) {
      return !tags.highlight || d.tag === tags.highlight;
    };
    edges = tags.edges.indexed[tags.highlight];
    opacity_scale = vis.opacity.scale.copy().domain(d3.extent(d3.values(edges)));
    _ref1 = opacity_scale.domain(), a = _ref1[0], b = _ref1[1];
    if (a === b) {
      (function(v) {
        return opacity_scale = function(n) {
          return v;
        };
      })(opacity_scale.range()[1]);
    }
    if (selection == null) {
      selection = vis.cloud.selectAll('text').data(vis.data, function(d) {
        return d.tag;
      });
    }
    return selection.transition().duration(1000).style('opacity', function(d) {
      if (hl_check(d)) {
        return vis.opacity.highlight;
      }
      if (edges[d.tag] == null) {
        return vis.opacity.unrelated;
      }
      return opacity_scale(edges[d.tag]);
    });
  };

  draw = function(data, bounds) {
    var exit_group, exit_group_node, scale, text, text_transition;
    scale = bounds ? Math.min(vis.w / Math.abs(bounds[0].x - vis.w / 2), vis.w / Math.abs(bounds[1].x - vis.w / 2), vis.h / Math.abs(bounds[0].y - vis.h / 2), vis.h / Math.abs(bounds[1].y - vis.h / 2)) / 2 : 1;
    vis.data = data;
    vis.status_counter = 0;
    text = vis.cloud.selectAll('text').data(data, function(d) {
      return d.tag;
    });
    text_transition = text.transition().duration(1000).attr('transform', function(d) {
      return 'translate(' + [d.x, d.y] + ')rotate(' + d.rotate + ')';
    }).style('font-size', function(d) {
      return d.size + 'px';
    });
    draw_hl_fade(text_transition);
    text_transition = text.enter().append('text').attr('text-anchor', 'middle').attr('transform', function(d) {
      return 'translate(' + [d.x, d.y] + ')rotate(' + d.rotate + ')';
    }).style('font-size', function(d) {
      return d.size + 'px';
    }).on('click', function(d) {
      return focus(d);
    }).style('opacity', 1e-6);
    draw_hl_fade(text_transition);
    text.style('font-family', function(d) {
      return d.font;
    }).style('fill', function(d) {
      return vis.fill(d.tag);
    }).text(function(d) {
      return d.tag;
    });
    exit_group = vis.bg.append('g').attr('transform', vis.cloud.attr('transform'));
    exit_group_node = exit_group.node();
    text.exit().each(function() {
      return exit_group_node.appendChild(this);
    });
    exit_group.transition().duration(1000).style('opacity', 1e-6).remove();
    return vis.cloud.transition().delay(250).duration(750).attr('transform', 'translate(' + [vis.w >> 1, vis.h >> 1] + ')scale(' + scale + ')');
  };

  draw_status = function() {
    vis.status_counter += 1;
    return vis.status.style('width', ((vis.status_counter / tags.sorted.length) * 100) + '%');
  };

  cloud = d3.layout.cloud().size([vis.w, vis.h]).spiral('archimedean').font('Impact').fontSize(function(d) {
    return vis.font_scale(d.value);
  }).timeInterval(Infinity).words(tags.sorted).text(function(d) {
    return d.tag;
  }).on('word', draw_status).on('end', draw).start();

  d3.select('#vis-shuffle').on('click', function(d) {
    tags.highlight = null;
    cloud.stop().start();
    return tags.links_box.style('display', 'none');
  });

  focus = function(d) {
    var links;
    tags.highlight = d.tag;
    draw_hl_fade();
    links = tags.links_box.select('ul').selectAll('li').data(tags.indexed[d.tag].links, function(d, i) {
      return d.url;
    });
    links.enter().append('li').append('a').attr('href', function(d) {
      return d.url;
    }).text(function(d) {
      return d.title || d.url;
    });
    links.exit().remove();
    return tags.links_box.style('display', 'block');
  };

  if ((typeof ffhome_links !== "undefined" && ffhome_links !== null) && ffhome_links.length) {
    backlog = d3.select('#backlog');
    backlog.select('ul').selectAll('li').data(ffhome_links).enter().append('li').append('a').attr('href', function(d) {
      return d.url;
    }).text(function(d) {
      return d.title || d.url;
    });
    backlog.style('display', 'block');
  }

}).call(this);
